// Code generated by "stringer -type=AudioType"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[FLAC-1]
	_ = x[MP3-2]
	_ = x[OGG-3]
	_ = x[WAV-4]
	_ = x[M4A-5]
	_ = x[AAC-6]
	_ = x[WMA-7]
	_ = x[AIFF-8]
	_ = x[AIF-9]
	_ = x[OPUS-10]
	_ = x[APE-11]
	_ = x[WV-12]
}

const _AudioType_name = "UnknownFLACMP3OGGWAVM4AAACWMAAIFFAIFOPUSAPEWV"

var _AudioType_index = [...]uint8{0, 7, 11, 14, 17, 20, 23, 26, 29, 33, 36, 40, 43, 45}

func (i AudioType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AudioType_index)-1 {
		return "AudioType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AudioType_name[_AudioType_index[idx]:_AudioType_index[idx+1]]
}
